theme: jekyll-theme-cayman
description: You can try some of my apps 😊
name: "Showcase"
title: Portfolio

universal_classifier_link: "https://lodeil-universal-classifier-app-at1jtk.streamlitapp.com/"
doc_parse_agent_link: "https://lodeil-doc-parse-agent-app-spncoa.streamlitapp.com/"
doc_extract_agent_link: "https://lodeil-doc-extract-agent-app-jt8h81.streamlitapp.com/"
the_namer_of_feelings_link: "https://lodeil-the-namer-of-feelings-app-c7it1h.streamlitapp.com/"
structure_doc_agent_link: "https://huggingface.co/spaces/Delchiga/structure_doc_agent"

github:
  is_project_page: false
